{
  "hash": "938e7d297c494551b80da8e6c991ee8c",
  "result": {
    "engine": "knitr",
    "markdown": "---\nlesson: Statistik 5\nknitr:\n  opts_chunk: \n    collapse: false\nmusterloesung: true\n---\n\n\n\n\n\n# Statistik 5: Übung\n\n**Datensatz *polis.csv***\n\nDer Datensatz polis.csv beschreibt für 19 Inseln im Golf von Kalifornien, ob \nEidechsen der Gattung Uta vorkommen (presence/absence: PA) in Abhängigkeit von \nder Form der Inseln (Verhältnis Umfang zu Fläche: RATIO)\n\nBitte prüft mit einer logistischen Regression, ob und ggf. wie die Inselform die Präsenz der Eidechsen beinflusst\n\n\n::::{.content-hidden unless-meta=\"musterloesung\"}\n:::{.callout-note}\n\n[Demoscript herunterladen (.R)](../purl/Statistik5_Uebung.R){.dld}\n\n[Demoscript herunterladen (.qmd)](../purl/Statistik5_Uebung.qmd){.dld}\n\n\n- [Lösungstext als Download](Statistik5_Loesung.pdf)\n\n\n\n## Musterlösung Übung 5\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(\"readr\")\nlibrary(\"ggplot2\")\nlibrary(\"dplyr\")\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\npolis <- read_delim(\"datasets/stat/polis.csv\", delim = \";\") |>\n  mutate(across(where(is.character), as.factor))\n                                     \nstr(polis)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ntibble [19 × 3] (S3: tbl_df/tbl/data.frame)\n $ ISLAND: Factor w/ 19 levels \"Angeldlg\",\"Bahiaan\",..: 5 6 7 8 9 10 11 12 14 15 ...\n $ RATIO : num [1:19] 15.41 5.63 25.92 15.17 13.04 ...\n $ PA    : num [1:19] 1 1 1 0 1 0 0 0 0 1 ...\n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(polis)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      ISLAND       RATIO             PA        \n Angeldlg: 1   Min.   : 0.21   Min.   :0.0000  \n Bahiaan : 1   1st Qu.: 5.86   1st Qu.:0.0000  \n Bahiaas : 1   Median :15.17   Median :1.0000  \n Blanca  : 1   Mean   :18.74   Mean   :0.5263  \n Bota    : 1   3rd Qu.:23.20   3rd Qu.:1.0000  \n Cabeza  : 1   Max.   :63.16   Max.   :1.0000  \n (Other) :13                                   \n```\n\n\n:::\n:::\n\n\n\n\nMan erkennt, dass polis 19 Beobachtungen von drei Parametern enthält, wobei \nISLAND ein Faktor mit den Inselnamen ist, während RATIO metrisch ist und PA \nnur 0 oder 1 enthält. Prädiktorvariable ist RATIO, abhängige Variable PA, \nmithin ist das korrekte statistische Verfahren eine logistische Regression (GLM).\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Definition des logistischen Modells\nglm_1 <- glm(PA ~ RATIO, family = \"binomial\", data = polis)\nsummary(glm_1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nglm(formula = PA ~ RATIO, family = \"binomial\", data = polis)\n\nCoefficients:\n            Estimate Std. Error z value Pr(>|z|)  \n(Intercept)   3.6061     1.6953   2.127   0.0334 *\nRATIO        -0.2196     0.1005  -2.184   0.0289 *\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 26.287  on 18  degrees of freedom\nResidual deviance: 14.221  on 17  degrees of freedom\nAIC: 18.221\n\nNumber of Fisher Scoring iterations: 6\n```\n\n\n:::\n:::\n\n\n\n\nModell ist signifikant (p-Wert in Zeile RATIO ist < 0.05). Jetzt müssen wir noch prüfen, ob es auch valide ist:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Modelldiagnostik für das gewählte Modell (wenn nicht signifikant, dann OK)\n1 - pchisq(glm_1$deviance, glm_1$df.resid)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.6514215\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(DHARMa)\nset.seed(123)\nsimulateResiduals(fittedModel = glm_1, plot = TRUE, n = 1000)\n```\n\n::: {.cell-output-display}\n![](Statistik5_Uebung_files/figure-html/unnamed-chunk-4-1.png){width=672}\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\nObject of Class DHARMa with simulated residuals based on 1000 simulations with refit = FALSE . See ?DHARMa::simulateResiduals for help. \n \nScaled residual values: 0.6566793 0.4936969 0.9419174 0.3367948 0.4871858 0.104532 0.2748362 0.4225525 0.17505 0.2594365 0.9131821 0.673212 0.5389095 0.5608408 0.2759569 0.6652148 0.2086698 0.3605077 0.7739565\n```\n\n\n:::\n:::\n\n\n\n\nIst ok\nJetzt brauchen wir noch die Modellgüte (Pseudo-R2):\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Modellgüte (pseudo-R²)\nlibrary(\"performance\")\nr2(glm_1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# R2 for Logistic Regression\n  Tjur's R2: 0.521\n```\n\n\n:::\n:::\n\n\n\n\nUm unser Modell zu interpretieren müssen wir noch in Betracht ziehen, dass \nwir nicht die Vorkommenswahrscheinlichkeit selbst, sondern logit (Vorkommenswahrscheinlichkeit) modelliert haben. Unser Ergebnis (die beiden Parameterschätzungen von oben, also 3.6061 und -0.2196) muss also zunächst in \netwas Interpretierbares übersetzt werden:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Steilheit der Beziehung in Modellen mit nur einem Parameter\nexp(glm_1$coef[2])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    RATIO \n0.8028734 \n```\n\n\n:::\n:::\n\n\n\n\n< 1, d. h. Vorkommenswahrscheinlichkeit sinkt mit zunehmender Isolation.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# LD50 für 1-Parameter-Modelle (hier also x-Werte, bei der 50% der Inseln \n# besiedelt sind)\nlibrary(MASS)\ndose.p(glm_1, p = 0.5)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n            Dose       SE\np = 0.5: 16.4242 3.055921\n```\n\n\n:::\n:::\n\n\n\n\nAm besten stellen wir auch unsere Funktionsgleichung dar. Dazu müssen wir das „Rohergebnis“ (mit P = Vorkommenswahrscheinlichkeit)\n\nln (P/ (1- P)) = 3.606 – 0.220 RATIO\n\nso umformen, dass wir links nur P stehen haben:\n\nP = exp(3.606 – 0.220 RATIO) / (1 + exp(3.606 – 0.220 RATIO))\n\nDas ist also unsere vorhergesagte Regressionsfunktion, die wir in einem letzten Schritt auch noch visualisieren können (und sollten):\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Ergebnisplots\nggplot(data = polis, aes(x = RATIO, y = PA)) +\n  geom_point() +\n  labs(x = \"Umfang-Flächen-Verhältnis\", y = \"Vorkommenswahrscheinlichkeit\") +\n  geom_smooth(method = \"glm\", method.args = list(family = \"binomial\")) +\n  theme_classic()\n```\n\n::: {.cell-output-display}\n![](Statistik5_Uebung_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n:::\n\n\n\n\n:::\n:::: \n",
    "supporting": [
      "Statistik5_Uebung_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}